import pytest
from datetime import timedelta

from ..common_conftest import *


EXAMPLE_VALID_SATISFYING_OBJECTIVE_VALUES = [None, 0., -1., 2154355.23453452]
EXAMPLE_VALID_MAX_ITERATIONS_WITHOUT_PROGRESS_VALUES = [None, 0, 1, 1000]
EXAMPLE_INVALID_MAX_ITERATIONS_WITHOUT_PROGRESS_VALUES = [-1, -100]
EXAMPLE_VALID_MAX_TIME_WITHOUT_PROGRESS_VALUES = [None, timedelta(microseconds=1), timedelta(seconds=9)]
